name: Deploy Multi-Environment

on:
  push:
    branches:
      - develop
      - main

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main'
    concurrency:
      group: ${{ github.repository }}-deploy-dev
      cancel-in-progress: false
    runs-on: ubuntu-latest

    steps:
      - name: Set lowercase OWNER and image name
        id: vars
        run: |
          echo "OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV
          echo "IMAGE_NAME=ghcr.io/${GITHUB_REPOSITORY_OWNER,,}/van-app-dev:latest" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: zWalterli
          password: ${{ secrets.GIT_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.IMAGE_NAME }}

      - name: SSH Deploy DEV
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_DEV_HOST }}
          username: ${{ secrets.VPS_DEV_USER }}
          key: ${{ secrets.VPS_DEV_SSH_KEY }}
          script: |
            set -xe

            export GITHUB_USER="zWalterli"
            export GIT_PAT="${{ secrets.GIT_PAT }}"
            export IMAGE_NAME="${{ env.IMAGE_NAME }}"

            echo "DEBUG: GITHUB_USER='$GITHUB_USER'"
            echo "DEBUG: GIT_PAT length='${#GIT_PAT}'"
            echo "DEBUG: IMAGE_NAME='$IMAGE_NAME'"

            echo "🚀 Atualizando código"
            cd ~/deploy/dev/infra
            git remote set-url origin https://github.com/MinhaVan/infra.git
            git fetch origin
            git checkout develop
            git reset --hard origin/develop

            echo "📦 Parando container antigo"
            cd ./APIs
            docker compose stop van-app-dev || true
            docker compose rm -f van-app-dev || true

            echo "📥 Removendo imagem antiga localmente"
            docker rmi "$IMAGE_NAME" || true

            echo "$GIT_PAT" | docker login ghcr.io -u "$GITHUB_USER" --password-stdin

            echo "📥 Puxando nova imagem do registry"
            docker pull "$IMAGE_NAME"

            echo "🚀 Subindo container com nova imagem"
            docker compose up -d van-app-dev

          debug: true
